[package]
name = "dungeon_crawl_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
legion = "=0.3.1"
rand = "0.8.5"
log = "0.4.21"
serde = "1.0.198"
ron = "0.8.1"
